services:
  mysql:
    image: mysql:latest
    container_name: ig_store_db
    restart: always
    # ports: 
    #   - "3306:3306"
    env_file: .env
    volumes: 
      - ./db:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  wordpress:
    image: wordpress:5.8.1-php8.0-fpm-alpine
    container_name: ig_store_wp
    restart: always
    depends_on: 
      - mysql
    volumes: 
      - ./wordpress:/var/www/html
      - ./igenomix_store:/var/www/html/wp-content/themes/igenomix_store/
      - ./etc/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file: .env
    environment: 
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE 
      - WORDPRESS_TABLE_PREFIX=$WP_TABLE_PREFIX

  nginx:
    image: nginx:1.21.3-alpine
    container_name: ig_store_nginx
    restart: always
    depends_on:
      - wordpress
      - mysql
    ports: 
      - "80:80"
    volumes: 
      - ./etc/ig_store.conf:/etc/nginx/conf.d/ig_store.conf
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./wordpress:/var/www/html
      - ./igenomix_store:/var/www/html/wp-content/themes/igenomix_store/